services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - ENVIRONMENT=docker

  chrome:
    image: selenium/node-chrome:4.27.0-20241204
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false

  edge:
    image: selenium/node-edge:4.27.0-20241204
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false

  firefox:
    image: selenium/node-firefox:4.27.0-20241204
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false

  selenium-hub:
    image: selenium/hub:4.27.0-20241204
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
