@url = http://audiencias.passoz.tech

#1066543-65.2024.8.26.0506
#1002303-27.2024.8.26.0390
#1014672-66.2024.8.26.0127

#0808803-63.2024.8.19.0075


@processorj = 0808803-63.2024.8.19.0075
@processosp = 0011092-87.2024.8.26.0016
@processotj = 0181718-82.2024.8.19.0001
@processoal = 0702508-67.2025.8.02.0001
@processoba = 0009443-83.2025.8.05.0001

@auth = Basic publico:gondim@098


###
GET {{url}}/audiencia?processo={{processorj}}
Authorization: {{auth}}

###
GET {{url}}/audiencia?processo={{processosp}}

###
GET {{url}}/audiencia?processo={{processotj}}

###
GET {{url}}/audiencia?processo={{processoal}}

###
GET {{url}}/audiencia?processo={{processoba}}

###
GET https://www3.tjrj.jus.br/consultaprocessual/#/consultapublica?numProcessoCNJ={{processotj}}